### ISSUE TITLE
TransactionForm / Create input compnent - Title

### ISSUE THREAD

**Issue by earlyoonj** [whaleap/expense-scheduler#12]
# Requirement
- icon field
- multiple text field
    - responsive size
    - create & remove

# Todo
- [x] icon field styling
- [x] input field styling
- [x] forwardRef for titles
- [x] forwardRef for icon
- [x] create & remove title input
