### ISSUE TITLE
Store / implement Budget, Transaction, Category state management

### ISSUE THREAD

**Issue by earlyoonj** [whaleap/expense-scheduler#2]
# Requirement
- state management for budget, transaction, category

# Todo
## Budget
- BudgetSlice
    - [x] set initial state
- BudgetActions
    - [x] replace total amount
    - [x] update total amount
## Transaction
- TrasnactionSlice
    - [x] set initial state
- TransactionActions
    - [x] addTransaction
## Category
- CategorySlice
    - [x] set initial state
- CategoryActions
    - [x] updateAmount

**Comment by earlyoonj** [comment]
# Working Log
- BudgetState
    ```javascript
    {
        id: string;
        isRepeating: boolean;
        startDate: Date;
        endDate: Date;
        total: Amount;
        transactions: Transaction[];
    }[]
    ```
