### ISSUE TITLE
Setup / Setup Basic Structure

### ISSUE THREAD

**Issue by jessie129j** [whaleap/expense-scheduler#20]
# Description
Setup basic structure of server

# Todo
- [x] Create index.js
- [x] Create and connect to MongoDB database
- [x] Create folders (models, routes, controllers)
- [x] Create and teat testAPI
