### ISSUE TITLE
Authenciation / Setup session based authentication

### ISSUE THREAD

**Issue by jessie129j** [whaleap/expense-scheduler#22]
# Description
Setup session based authentication

# Todo
- [ ]  Create User model
- [ ] Create Login, Register, Logout API
- [ ]  Create filestore session _(it will be replaced with Redis cloud session later)_
- [ ]  Use passport module to authenticate
- [ ]  Test login, register, logout API
