### ISSUE TITLE
DateStatus / Implement calendar interaction

### ISSUE THREAD

**Issue by earlyoonj** [whaleap/expense-scheduler#5]
# Requirement
- Show daily expense/income
- Add daily transaction by clicking date

# Todo
- [x] Get budget date info → calendar
- [x] OnClick date → Scroll & Show TransactionForm with date value
- [x] Transaction data → Calculate daily data from transactionSlice
